<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4rbLsbx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4rbLsbx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4rbLsbx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4rbLsbx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container4rbLsbx\srcDevDebugProjectContainer(array(
    'container.build_hash' => '4rbLsbx',
    'container.build_id' => '7eca4abc',
    'container.build_time' => 1536410348,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4rbLsbx');
